apiVersion: v1
kind: Namespace
metadata:
  name: c2c-hpe-mark-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-hpe-mark-deployment
  namespace: c2c-hpe-mark-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:1a125b1684949847a80ca237f9b80c5c5f4d2e2c

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-hpe-mark-label
  name: c2c-hpe-mark-service
  namespace: c2c-hpe-mark-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---